### PR TITLE
Tuple bridging

### PR DESCRIPTION
**Pull request by erwald**
Given the constraints, this was the best up with which I was able to come ... I leave it to you to decide whether its useful enough to include. :)

Global functions abound, because it is neither possible to extend `RACNTuple`s with generics (we recognise this problem from `RACSignal` bridging) nor to extend native Swift tuples. So if we want to keep generic types, we are left with global functions (until Swift generics are improved).

Here is a usage example:

```swift
// ObjC -> Swift
let signal = RACSignal<RACTwoTuple<NSNumber, NSString>>.return(RACTwoTuple<NSNumber, NSString>.pack(0, ""))
let bridgedProducer = bridgedSignalProducer(from: signal).skipNil()

let swiftProducerOldWay = bridgedProducer.map { ($0.first, $0.second) } // SignalProducer<(NSNumber?, NSString?), AnyError>
let swiftProducer = bridgedProducer.map(bridgedTuple) // SignalProducer<(NSNumber?, NSString?), AnyError>
```

In the end, I decided against including a conversion method for Swift tuples -> `RACTuple` objects, since it was tricky to figure out how to handle tuples of optionals nicely and since the benefits would have been minor:

```swift
// SCRAPPED:

// Swift -> ObjC
let producer = SignalProducer<(NSNumber, NSString), NSError>(value: (0, ""))

let racSignalOldWay = producer.map { RACTwoTuple.pack($0.0, $0.1) }.toRACSignal() // RACSignal<RACTwoTuple<NSNumber, NSString>>
let racSignal = producer.map(toRACTuple).toRACSignal() // RACSignal<RACTwoTuple<NSNumber, NSString>>
```

Also updates the ReactiveObjC dependency to version 3.0.0.

### CODE REVIEW

**Comment by erwald** [comment]
@mdiep @andersio @erichoracek Thoughts?

**Comment by erichoracek** [comment]
After thinking about this a little bit more, would it make sense to expose variants of the SignalProducer/Signal/Action bridging functions with tuple bridging built in? E.g.:

```swift
public func bridgedSignalProducer<A, B>(from signal: RACSignal<RACTwoTuple<A, B>>, file: String = #file, line: Int = #line) -> SignalProducer<(A?, B?)?, AnyError> {
	return _bridgedSignalProducer(from: signal).map { $0 != nil ? bridgedTuple(from: $0!) : nil }
}

// etc...

private func _bridgedSignalProducer<Value>(from signal: RACSignal<Value>, file: String = #file, line: Int = #line) -> SignalProducer<Value?, AnyError> {
    // ... Default implementation, without specific types
}
```

**Comment by erwald** [comment]
Yeah, that's a good idea. I'll give it a shot tonight or tomorrow. Of course, it would be a breaking change.

**Comment by erwald** [comment]
@mdiep @erichoracek I've updated the PR so that the following is now possible:

```swift


let signal = RACSignal<RACTwoTuple<NSNumber, NSString>>.return(RACTwoTuple<NSNumber, NSString>.pack(0, ""))
let bridgedProducer = bridgedSignalProducer(from: signal) // SignalProducer<(NSNumber?, NSString?)?, AnyError>

let signal2 = RACSignal<RACThreeTuple<NSNumber, NSString, NSNumber>>.return(RACThreeTuple<NSNumber, NSString, NSNumber>.pack(0, "", nil))
let bridgedProducer2 = bridgedSignalProducer(from: signal2) // SignalProducer<(NSNumber?, NSString?, NSNumber?)?, AnyError>

let signal3 = RACSignal<RACUnit>.return(RACUnit.default())
let bridgedProducer3 = bridgedSignalProducer(from: signal3) // SignalProducer<RACUnit?, AnyError>
```

Do have another look when you find some time!

**Comment by erwald** [comment]
Also, as I mentioned, I suppose it is possible for this to break existing code (which may rely on getting, say, a `RACTwoTuple` from a bridged SignalProducer). So I suppose these changes should go in a new major version if accepted?

**Comment by erichoracek** [comment]
This looks great! I would imagine that this would require a new major version of ReactiveObjCBridge as we've updated to a new major version of ReactiveObjC. Of course, that can come in a new PR.

Regarding getting this merged, It looks like the `ReactiveObjCBridge.podspec` file will need to be updated to include a reference to `ReactiveObjC` `3.0.0` get CI passing as well.

**Comment by erwald** [comment]
@erichoracek Done!

Can you think of anything else to add before releasing v2.0.0?

**Comment by andersio** [comment]
Rebase on `master` should get the tests up and running.

**Comment by erichoracek** [comment]
This looks good to me! I can't think of anything off of the top of my head that would make sense for v2.0.

**Comment by andersio** [comment]
Hmm, #26?

**Comment by mdiep** [comment]
Maybe merge this and then tackle the changes in #26 if we want them?

@erichoracek I'm happy to let you head this up if you're interested!

**Comment by erichoracek** [comment]
Ah yes, #26 should definitely go in 2.0! I was thinking just about the changes that were introduced in RACObjC 3.0 and whether anything else in there needing bridging. I'll go ahead and merge this and take a look at #26.

**Pull request merged**
