### PR TITLE
Update ReactiveSwift to 2.0.1.

### PR DESCRIPTION
**Pull request by andersio**

### CODE REVIEW

**Comment by mdiep** [comment]
```
❌  /Users/travis/build/ReactiveCocoa/ReactiveObjCBridge/ReactiveObjCBridgeTests/ObjectiveCBridgingSpec.swift:176:22: ambiguous reference to member 'bridged'
                                        let racSignal = producer.bridged
                                                        ^~~~~~~~
```

**Comment by andersio** [comment]
@ikesyo It seems the new `SignalProducer.init` overloads might be related to the regression. Would you mind to have a look?

https://github.com/ReactiveCocoa/ReactiveObjCBridge/pull/37/commits/ffa13d8eb670d487d0b6dcb2a89ecc6d2e1d467a#diff-d4bcc714583ed72e3a35d2dd93420710R169

**Comment by ikesyo** [comment]
@andersio It will be true that that is related to https://github.com/ReactiveCocoa/ReactiveSwift/pull/497. Looks like adding the overloads somehow affect the overload resolution of the followings:

- `public init(_ action: @escaping () -> Value)` in `public struct SignalProducer<Value, Error: Swift.Error>` ([here](https://github.com/ReactiveCocoa/ReactiveSwift/blob/cc4ef960b00be9c0e7166ee3c1f1b1ff7a2817d7/Sources/SignalProducer.swift#L122))
- `public init(_ action: @escaping () -> Result<Value, Error>)` in `public struct SignalProducer<Value, Error: Swift.Error>` ([here](https://github.com/ReactiveCocoa/ReactiveSwift/blob/cc4ef960b00be9c0e7166ee3c1f1b1ff7a2817d7/Sources/SignalProducer.swift#L138))
- `public init(_ action: @escaping () throws -> Value)` in `extension SignalProducer where Error == AnyError` ([here](https://github.com/ReactiveCocoa/ReactiveSwift/blob/cc4ef960b00be9c0e7166ee3c1f1b1ff7a2817d7/Sources/SignalProducer.swift#L295))

I think that it may be good to revisit https://github.com/ReactiveCocoa/ReactiveSwift/pull/346.

**Comment by ikesyo** [comment]
As a side note, `() -> Value` is a subtype of `() throws -> Value`.

**Pull request merged**
