### PR TITLE
Release/1.1.0

### PR DESCRIPTION
**Pull request by erwald**
I had to update Quick (to 7.0.1) as well, as in #29.

### CODE REVIEW

**Comment by mdiep** [comment]
The `pod lint` CI job failed. Can you try adding `pod repo update` to the `.travis.yml`?

**Comment by ikesyo** [comment]
We already have `pod repo update --silent`. I'm not sure what's wrong 🤔

**Comment by erwald** [comment]
Hm, yes, not quite sure why it's failing. I'll have a look at it later today.

**Comment by erwald** [comment]
Locally it seems to work:

```sh
[ReactiveObjCBridgePodTest] pod install                                                                                                                                 master  ✱
Analyzing dependencies
Pre-downloading: `ReactiveObjCBridge` from `https://github.com/erwald/ReactiveObjCBridge.git`, branch `release/1.1.0`
Downloading dependencies
Installing ReactiveObjC (3.0.0)
Installing ReactiveObjCBridge (1.1.0)
Installing ReactiveSwift (1.1.5)
Installing Result (3.2.3)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `ReactiveObjCBridgePodTest.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
```

I'm at a loss. I'll don't know if it's considered kosher to just trigger another build, but I'll try that anyway.

**Comment by erwald** [comment]
Hmm. Could it be that it's failing because there's no `1.1.0` tag set yet?

**Comment by ikesyo** [comment]
No, contrary to `pod spec lint`, `pod lib lint` is okay for that case.

**Comment by mdiep** [comment]
Not sure why it worked now, but it did! 😅

**Comment by mdiep** [comment]
@ikesyo Could you pushing the podspec update? 🙏

**Comment by erwald** [comment]
@ikesyo Would it be possible to push the new spec to the CocoaPods master repo?

**Comment by ikesyo** [comment]
I'm sorry for the late, done 🚀

**Pull request merged**
